### PR TITLE
Add bash analyzer

### PR DESCRIPTION
**Pull request by glennj**
As requested in exercism/bash-analyzer#1

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Comment by glennj** [comment]
I'm seeing this on the /maintaining/submissions page: is this normal?
```
Bash
Error Handling
passed
exceptioned

STDERR:
------
Unable to find image '681735686245.dkr.ecr.eu-west-2.amazonaws.com/bash-representer:production' locally
docker: Error response from daemon: pull access denied for 681735686245.dkr.ecr.eu-west-2.amazonaws.com/bash-representer, repository does not exist or may require 'docker login': denied: User: arn:aws:sts::681735686245:assumed-role/tooling-invoker-ec2/i-0bd31c24d4e55796e is not authorized to perform: ecr:BatchGetImage on resource: arn:aws:ecr:eu-west-2:681735686245:repository/bash-representer.
See 'docker run --help'.


Exception Details:
------
{"message"=>"Exit status: 125", "backtrace"=>nil}

exceptioned

STDERR:
------
Unable to find image '681735686245.dkr.ecr.eu-west-2.amazonaws.com/bash-analyzer:production' locally
docker: Error response from daemon: manifest for 681735686245.dkr.ecr.eu-west-2.amazonaws.com/bash-analyzer:production not found: manifest unknown: Requested image not found.
See 'docker run --help'.


Exception Details:
------
{"message"=>"Exit status: 125", "backtrace"=>nil}
```

**Comment by iHiD** [comment]
Yes. As the analyzer hasn't yet been deployed and so doesn't exist.

**Comment by glennj** [comment]
I found the mention of `bash-representer` curious. Is that just how the terraform deployment is configured?

**Comment by iHiD** [comment]
Yeah, so currently each submission creates a job for testing, analysing and representation. The tooling then tries to run each one. If the tool doesn't exist, it exceptions, which doesn't effect the user's experience (for analysis and representation it acts as a "no feedback found" effectively). Which is what you're seeing there.

**Pull request merged**
